export const CHIPS_TAGS = {
  HTML: "html",
  CSS: "css",
  JAVASCRIPT: "javascript",
  REACT: "react",
  PYTHON: "python",
  FLASK: "flask",
  POSTGRE: "postgre",
  CYPRESS: "cypress",
  VITEST: "vitest",
  BOOTSTRAP: "bootstrap",
  ASTRO: "astro",
  C: "c",
  JAVA: "java",
  JWT: "jwt",
  MARIADB: "mariadb",
  MUI: "mui",
  MYSQL: "mysql",
  NEXT: "next",
  REACT_ROUTER: "react-router",
  SPRING: "spring",
  TYPESCRIPT: "typescript",
  TAILWIND: "tailwind",
  REDUX: "redux",
};
